import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline': '#857468',
        'surface-dim': '#e0d9d3',
        'error': '#ba1a1a',
        'primary': '#894d14',
        'tertiary': '#29674a',
        'on-primary-fixed-variant': '#6e3900',
        'inverse-primary': '#ffb77e',
        'primary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#95d4b1',
        'on-tertiary-fixed-variant': '#0d5136',
        'surface-bright': '#fff8f4',
        'secondary-fixed': '#d5e3ff',
        'secondary': '#395f94',
        'error-container': '#ffdad6',
        'on-surface-variant': '#524439',
        'surface-container': '#f4ece7',
        'inverse-surface': '#33302c',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#002113',
        'surface-tint': '#8c4f16',
        'surface-container-low': '#faf2ed',
        'on-secondary-fixed-variant': '#1e477b',
        'inverse-on-surface': '#f7efea',
        'on-secondary-container': '#284f83',
        'surface-variant': '#e9e1dc',
        'on-primary-container': '#fffbff',
        'on-error': '#ffffff',
        'on-tertiary-container': '#f6fff6',
        'tertiary-fixed': '#b0f1cc',
        'on-primary-fixed': '#2f1500',
        'secondary-container': '#9ec2fe',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'outline-variant': '#d8c3b5',
        'on-surface': '#1e1b18',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#efe7e1',
        'on-secondary-fixed': '#001c3b',
        'primary-container': '#a6652b',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#a7c8ff',
        'surface': '#fff8f4',
        'tertiary-container': '#438062',
        'on-background': '#1e1b18',
        'background': '#fff8f4',
        'surface-container-highest': '#e9e1dc',
        'primary-fixed-dim': '#ffb77e',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      fontFamily: {
        'headline': ['var(--font-newsreader)', 'serif'],
        'body': ['var(--font-inter)', 'sans-serif'],
        'label': ['var(--font-inter)', 'sans-serif'],
        'mono': ['var(--font-jetbrains-mono)', 'monospace'],
      },
      boxShadow: {
        'editorial': '0px 24px 48px rgba(30, 27, 24, 0.06)',
        'warm': '0 1px 3px rgba(26, 23, 20, 0.06)',
      },
      backgroundImage: {
        'scanline': 'repeating-linear-gradient(90deg, transparent, rgba(0,0,0,.03), transparent 1px)',
      },
    },
  },
  plugins: [],
};

export default config;
