import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        outline: 'var(--color-outline)',
        'surface-dim': 'var(--color-surface-dim)',
        error: 'var(--color-error)',
        primary: 'var(--color-primary)',
        tertiary: 'var(--color-tertiary)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-bright': 'var(--color-surface-bright)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        secondary: 'var(--color-secondary)',
        'error-container': 'var(--color-error-container)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'surface-container': 'var(--color-surface-container)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'on-primary': 'var(--color-on-primary)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-error': 'var(--color-on-error)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'secondary-container': 'var(--color-secondary-container)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-secondary': 'var(--color-on-secondary)',
        'outline-variant': 'var(--color-outline-variant)',
        'on-surface': 'var(--color-on-surface)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'primary-container': 'var(--color-primary-container)',
        'on-error-container': 'var(--color-on-error-container)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        surface: 'var(--color-surface)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-background': 'var(--color-on-background)',
        background: 'var(--color-background)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        success: 'var(--color-success)',
        'on-success': 'var(--color-on-success)',
      },
      borderRadius: {
        'DEFAULT': 'var(--radius)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      fontFamily: {
        'headline': ['var(--font-newsreader)', 'serif'],
        'body': ['var(--font-inter)', 'sans-serif'],
        'label': ['var(--font-inter)', 'sans-serif'],
        'mono': ['var(--font-jetbrains-mono)', 'monospace'],
      },
      boxShadow: {
        'editorial': '0px 24px 48px rgba(30, 27, 24, 0.06)',
        'warm': '0 1px 3px rgba(26, 23, 20, 0.06)',
      },
      backgroundImage: {
        'scanline': 'repeating-linear-gradient(90deg, transparent, rgba(0,0,0,.03), transparent 1px)',
      },
    },
  },
  plugins: [],
};

export default config;
